# Generated by Django 5.0.4 on 2024-04-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_food_cart_food_id_rename_user_cart_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='food_id',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
