# Generated by Django 5.0.4 on 2024-04-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('food_star', models.DecimalField(decimal_places=2, max_digits=3)),
                ('food_vote', models.IntegerField()),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food_discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('food_description', models.CharField(max_length=255)),
                ('food_status', models.CharField(choices=[('available', 'Available'), ('sold_out', 'Sold Out'), ('coming_soon', 'Coming Soon')], max_length=20)),
                ('food_type', models.CharField(choices=[('appetizer', 'Appetizer'), ('main_course', 'Main Course'), ('dessert', 'Dessert')], max_length=20)),
                ('food_category', models.CharField(max_length=255)),
                ('food_src', models.ImageField(upload_to='food_images/')),
            ],
        ),
    ]
